[package]
name = "pinboard"
version = "0.1.0"
authors = ["David O'Rourke <david.orourke@gmail.com>"]

[dependencies]
config = "0.7"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
